# Generated by Django 4.1 on 2023-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='cse', max_length=100),
            preserve_default=False,
        ),
    ]
